### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by remicollet** [DataDog/dd-trace-php#212]
Build fails.

```
In file included from /opt/remi/php73/root/usr/include/php/Zend/zend.h:29,
                 from /opt/remi/php73/root/usr/include/php/main/php.h:33,
                 from /dev/shm/BUILD/php73-php-pecl-datadog-trace-0.8.1/NTS/src/ext/dispatch_compat_php7.c:1:
/dev/shm/BUILD/php73-php-pecl-datadog-trace-0.8.1/NTS/src/ext/dispatch_compat_php7.c: In function 'ddtrace_dispatch_store':
/dev/shm/BUILD/php73-php-pecl-datadog-trace-0.8.1/NTS/src/ext/dispatch_compat_php7.c:46:91: error: 'HASH_FLAG_PERSISTENT' undeclared (first use in this function); did you mean 'HASH_FLAG_CONSISTENCY'?
     ddtrace_dispatch_t *dispatch = pemalloc(sizeof(ddtrace_dispatch_t), lookup->u.flags & HASH_FLAG_PERSISTENT);
                                                                                           ^~~~~~~~~~~~~~~~~~~~
/opt/remi/php73/root/usr/include/php/Zend/zend_alloc.h:193:38: note: in definition of macro 'pemalloc'
 #define pemalloc(size, persistent) ((persistent)?__zend_malloc(size):emalloc(size))
                                      ^~~~~~~~~~
/dev/shm/BUILD/php73-php-pecl-datadog-trace-0.8.1/NTS/src/ext/dispatch_compat_php7.c:46:91: note: each undeclared identifier is reported only once for each function it appears in
     ddtrace_dispatch_t *dispatch = pemalloc(sizeof(ddtrace_dispatch_t), lookup->u.flags & HASH_FLAG_PERSISTENT);
                                                                                           ^~~~~~~~~~~~~~~~~~~~
/opt/remi/php73/root/usr/include/php/Zend/zend_alloc.h:193:38: note: in definition of macro 'pemalloc'
 #define pemalloc(size, persistent) ((persistent)?__zend_malloc(size):emalloc(size))

```

**Comment by SammyK** [comment]
Thanks for reporting this @remicollet! We're working on adding 7.3 support. :)

**Comment by pawelchcki** [comment]
7.3 is compiling successfully 🎉 thanks @SammyK for fix  and @remicollet for reporting
